package sbnz.integracija;

import com.security.hospital.model.drools.Test;
import com.security.hospital.dto.*;
import java.util.ArrayList;

global ArrayList<ActivatedLogAlarmDTO> activatedAlarms;

rule "Test-Hospital"
	agenda-group "alarms"
	no-loop
	when 
		$logMessage: LogMessageDTO($content: content) and
		$configuredAlarm: LogAlarmDTO( $content.contains(whenContentHas) )
	then
		System.out.println("ACTIVATED ALARM, LOG: " + $logMessage + ", ALARM: " + $configuredAlarm.getName());
		activatedAlarms.add(new ActivatedLogAlarmDTO($configuredAlarm.getId(), $configuredAlarm.getName()));
end